sudo: required
services:
- docker
script:
- docker build --tag "$IMAGE_NAME" .
after_script:
- docker images
before_deploy:
- docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${TRAVIS_BUILD_NUMBER}"
deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${TRAVIS_BUILD_NUMBER}"
  on:
    branch: master
env:
  global:
  - IMAGE_NAME=npiper/certbot-nginx
  - secure: LC+Qw/eTpSXr/DoNsd+xr3YZMW+ekHVt7W6hqPwarbtKb3hH701QgshRtG02c/uFUoXQ18H1M4ufvB3NBi9pz57QG++uyEllgPQIHrLqfrZuTuSGvCGFvm3gV1qf0IkzUe99yZwkiPUUbnyCHUXILDK6U2ZK2V0w1jL8OxbXj3DV6cqTo/nfsgTf9vP8a3clQqxhSEimcq+uaWdlSw6rCV4jwudKJqZFoE8HK8EYSj0AkjNKieXm1CdDGlZU3gGB83+AiwGcbynRRfDiaFdHcUeGncn1EAw2XuGwYrwlMw88nugoEvX+U2hA8CgzuXblvAD7l7KMXPq5d8p/Sco9xYFAfHK42RLKjVqEer+6HaN0mrSZbkc2+MZyD9hDnOk7LOp6+5LvDSVtsh6TtZj91cwm0FB3/92SGFth7Rg+XTIR0AA7RJkCBSnylFfI4yGaFNxyomYaz6mDv6Wh9zT3PAZyiKxDruEHVuc66hfpqiXv/6kKNx2gBn2ZyxRDHRcP9NWz91oQfSDdzsOa6NT0MrcWP1x6U2xWoCDHFl6fa9QOXqnd/eM9UspL6YtOha+3cagZ+1WPn1L6Y6jKrzN96uCElMjvON4oFjeGneah6q1I3MCJmi2/d9/VIquAAkOBLcx2EZC1STmJQKW+Fz6MVuj/jebZtoC1+SCsiRlL53k=
  - secure: grA3BdBr44zCYIVfGzABrzLrG5tP9nLxlflf1FPuqn0723+VP9bkHr/xD8l8jVCYQVP5gSnd8fdJbahIrGneka7BUnsEj/mcn8rreAoQ+BWwcOkzCf3CZ2SxWZdhV1OUg6vfrr1004uyqT0FqwcHKUUpI4vv2WMYNNFfxcbWtYzm1HvM6wrRjMxY5BfOtTw4owkskmHz1vtZgXEWQUgaNy/rGrr9k2I41DN+w3mrZBWiIHiE7SCFyDYHTUdmPpauXVkchQygw+X79QdVRtb2oiCw8QKL/IEDyqecwxiMTig1ZkfqbKNzY5y1D3qNWVr56gi4T8P+kVw+2MwR/nfUaYR2t+sokvZ7AzAYPPrpOH9cDSK53XkRczvDRFI+RvfQBn+VEgYBvrjtL5I9mOK8ijMJ6yf3PizKY03LqBP9rYHAFDL2NER+OK9Trxx3Kiv3YTQbOiqFYFA4N9pV9Lpy2VJasBIngqEVfWOxqjnHjpSZRUbOyDWS5dZWcm8bZ1XsyUFGwiGJvV7knSpb4t8ur9Ki4WK8Wh+nlgsMzE0a1+JKB+ycugt9kVbWe2BoT2OSnbeONm4KhmYZOHLI2r6+DdI2YVrmI+Ct8xiuF94KWotg4PrGl/LeHajooYGaYvmb5u8sRkDlA3dYr0gM0OjHDDQskJ+GaCsafoXu71pbqVs=
